export const types = {
  FILL_POSTS: 'FILL_POSTS',
  FETCH_POSTS_ASYNC: 'FETCH_POSTS_ASYNC',
  CREATE_POST: 'CREATE_POST',
  CREATE_POST_ASYNC: 'CREATE_POST_ASYNC',
  CLEAR_POSTS: 'CLEAR_POSTS',
  REMOVE_POST_ASYNC: 'REMOVE_POST_ASYNC',
  REMOVE_POST: 'REMOVE_POST',
};
