export const types = {
  AUTHENTICATE: 'AUTHENTICATE',
  LOGIN_ASYNC: 'LOGIN_ASYNC',
  SIGNUP_ASYNC: 'SIGNUP_ASYNC',
  AUTHENTICATE_ASYNC: 'AUTHENTICATE_ASYNC',
  INITIALIZE: 'INITIALIZE',
  INITIALIZE_ASYNC: 'INITIALIZE_ASYNC',
  LOGOUT: 'LOGOUT',
  LOGOUT_ASYNC: 'LOGOUT_ASYNC',
};
